
language: node_js
node_js:
  - "stable"
services:
  - docker
script:
  - npm run fix:js
  - npm run lint:js
#   - sudo docker system prune -a -f
#   - git clone https://andrii482:$GithubToken@github.com/482solutions/woden-network.git
#   - cd woden-network && sudo chmod 777 ./deploy.sh && sudo ./deploy.sh
#   - cd ..
#   #  - sudo docker-compose -f docker-compose-test.yaml up --build --abort-on-container-exit

#   - sudo docker-compose up --build -d
#   - sleep 60
#   - cd ./e2e && npm i && npm run cypress:run
