---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICFzCCAb2gAwIBAgIURD6w6oRTyoNVnv20652LFjnXWtIwCgYIKoZIzj0EAwIw
          aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
          EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
          Y2Etc2VydmVyMB4XDTIzMDcxMDEyNTMwMFoXDTM4MDcwNjEyNTMwMFowaDELMAkG
          A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
          cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
          dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEH6G41QrN8ndm86Z7WZXisazU
          6PbZZlBA8ckKUMD4i1J1f9EwlZZtuDlVjbjiuC9JZFEtogCggWw41Ut+no8zOKNF
          MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
          FJTmlFdrV20S74ehmrasYPyCkRIwMAoGCCqGSM49BAMCA0gAMEUCIQDfQ8oZjcOr
          hovaiXYiXKyLYkqEhGGavrhN7xNAKDoQRgIgEla32/ppGQM3BLtLPHWVcOTp+SEk
          bO4YUEKNsdGdpC8=
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
      request-timeout: 1200001

affiliations:
   org1:
      - department1
      - department2

certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICFzCCAb2gAwIBAgIURD6w6oRTyoNVnv20652LFjnXWtIwCgYIKoZIzj0EAwIw
          aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
          EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
          Y2Etc2VydmVyMB4XDTIzMDcxMDEyNTMwMFoXDTM4MDcwNjEyNTMwMFowaDELMAkG
          A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
          cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
          dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEH6G41QrN8ndm86Z7WZXisazU
          6PbZZlBA8ckKUMD4i1J1f9EwlZZtuDlVjbjiuC9JZFEtogCggWw41Ut+no8zOKNF
          MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
          FJTmlFdrV20S74ehmrasYPyCkRIwMAoGCCqGSM49BAMCA0gAMEUCIQDfQ8oZjcOr
          hovaiXYiXKyLYkqEhGGavrhN7xNAKDoQRgIgEla32/ppGQM3BLtLPHWVcOTp+SEk
          bO4YUEKNsdGdpC8=
          -----END CERTIFICATE-----
              
    httpOptions:
      verify: false
