name: Docker

on:
  push: 
    branches:
  # Run tests for any PRs.
  pull_request:

#env:

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          mkdir cypress
          cd cypress
          git clone https://andrii482:{{ secret.woden_server_js_workflow_actions_repo }}@github.com/482solutions/woden-server-js.git  -b  WGRND-551 --single-branch 
          cd woden-server-js
          cd e2e
          npm i
          npm run cypress:run    

  
