name: Docker

on:
  push: 
    branches:
      - master
  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker-compose up --build -d 
          mkdir cypress
          cd cypress
          git clone https://andrii482:c0c5e002db7d9fc089c5091bdf5a23adff97391e@github.com/482solutions/woden-server-js.git  -b  WGRND-551 --single-branch 
          cd woden-server-js
          cd e2e
          npm i
          npm run cypress:run    

  
