# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
#     branches: [ master ]
  pull_request:
#     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run fix:js
    - run: npm run lint:js
    - run: sudo docker system prune -a -f
    - run: git clone https://andrii482:$GithubToken@github.com/482solutions/woden-network.git
    - run: cd woden-network && sudo chmod 777 ./deploy.sh && sudo ./deploy.sh
    - run: cd ..
  #  - sudo docker-compose -f docker-compose-test.yaml up --build --abort-on-container-exit
    - run: sudo docker-compose up --build -d
#     - run: sleep 60
    - run: cd ./e2e && npm i && npm run cypress:run
